# This is a basic workflow to help you get started with Actions

name: JAVA Project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    - types: opened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Pre_Test:
    runs-on: ubuntu_latest
    steps:
      - name: Print Event
        run: echo "${{ toJSON(github.event) }}"

  Test:
    needs: Pre_Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Test
        run: |
          javac Addition.java
          java Addition

          echo "Test Passed Successfully"

  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: |
          echo "Deploying code"
          echo "Deployment Successful"
